insert into city
values(1, 'Skopje'),
(2, 'Veles'),
(3, 'Demir Kapija'),
(4, 'Kavadarci'),
(5, 'Negotino'),
(6, 'Cveti Nikole'),
(7, 'Berovo'),
(8, 'Vinica'),
(9, 'Delchevo'),
(10, 'Kochani'),
(11, 'Makedonska Kamenica'),
(12, 'Pehchevo'),
(13, 'Probishtip'),
(14, 'Shtip'),
(15, 'Debar'),
(16, 'Kichevo'),
(17, 'Makedonski Brod'),
(18, 'Ohrid'),
(19, 'Struga'),
(20, 'Bogdanci'),
(21, 'Valandovo'),
(22, 'Gevgelija'),
(23, 'Radovish'),
(24, 'Strumica'),
(25, 'Bitola'),
(26, 'Demir Hisar'),
(27, 'Krushevo'),
(28, 'Prilep'),
(29, 'Resen'),
(30, 'Gostivar'),
(31, 'Tetovo'),
(32, 'Kratovo'),
(33, 'Kriva Palanka'),
(34, 'Kumanovo');

insert into municipality
values(1, 'Aerodrom'),
(2, 'Arachinovo'),
(3, 'Berovo'),
(4, 'Bitola'),
(5, 'Bogdanci'),
(6, 'Bogovinje'),
(7, 'Bosilovo'),
(8, 'Brvenica'),
(9, 'Butel'),
(10, 'Valandovo'),
(11, 'Vasilevo'),
(12, 'Vevchani'),
(13, 'Veles'),
(14, 'Vinica'),
(15, 'Vrapchishte'),
(16, 'Gazi Baba'),
(17, 'Gevgelija'),
(18, 'Gostivar'),
(19, 'Gradsko'),
(20, 'Debar'),
(21, 'Debrca'),
(22, 'Delchevo'),
(23, 'Demir Kapija'),
(24, 'Demir Hisar'),
(25, 'Dojran'),
(26, 'Dolneni'),
(27, 'Gjorche Petrov'),
(28, 'Zhelino'),
(29, 'Zelenikovo'),
(30, 'Zrnovci'),
(31, 'Ilinden'),
(32, 'Jegunovce'),
(33, 'Kavadarci'),
(34, 'Karbinci'),
(35, 'Karposh'),
(36, 'Kisela Voda'),
(37, 'Kichevo'),
(38, 'Konche'),
(39, 'Kochani'),
(40, 'Kratovo'),
(41, 'Kriva Palanka'),
(42, 'Krivogashtani'),
(43, 'Krushevo'),
(44, 'Kumanovo'),
(45, 'Lipkovo'),
(46, 'Lozovo'),
(47, 'Mavrovo i Rostushe'),
(48, 'Makedonska Kamenica'),
(49, 'Makeodnski brod'),
(50, 'Mogila'),
(51, 'Negotino'),
(52, 'Novaci'),
(53, 'Novo Selo'),
(54, 'Ohrid'),
(55, 'Petrovec'),
(56, 'Pehchevo'),
(57, 'Plasnica'),
(58, 'Prilep'),
(59, 'Probishtip'),
(60, 'Radovish'),
(61, 'Rankovce'),
(62, 'Resen'),
(63, 'Rosoman'),
(64, 'Saraj'),
(65, 'Sveti Nikole'),
(66, 'Sopishte'),
(67, 'Staro Nagorichane'),
(68, 'Struga'),
(69, 'Strumica'),
(70, 'Studenichani'),
(71, 'Tearce'),
(72, 'Tetovo'),
(73, 'Centar'),
(74, 'Centar Zhupa'),
(75, 'Chair'),
(76, 'Chashka'),
(77, 'Cheshinovo-Obleshevo'),
(78, 'Chucher-Sandevo'),
(79, 'Shtip'),
(80, 'Shuto Orizari');

insert into policystatus
values(1, 'Active'),
(2, 'Pending'),
(3, 'Approved'),
(4, 'Denied');

insert into usertype
values(1, 'salesman'),
(2, 'administrator'),
(3, 'manager'),
(4, 'finance'),
(5, 'liquidators'),
(6, 'damageAppraiser');

insert into insurancetype
values(1, 'VehicleInsurance'),
(2, 'BikeInsurance'),
(3, 'TravelHealthInsurance'),
(4, 'HouseHoldInsurance'),
(5, 'RealEstateInsurance'),
(6, 'CorporatePropertyInsurance'),
(7, 'LiabilityInsurance'),
(8, 'CorporateAccidentInsurance');

insert into subtype
values(1, 'Super Kasko', '1'),
(2, 'Full Kasko', '1'),
(3, 'Mini Kasko', '1'),
(4, 'Kasko Parking', '1'),
(5, 'FirstRisk Kasko', '1'),
(6, 'Start', '2'),
(7, 'Pro', '2'),
(8, 'Premium', '2'),
(9, 'Mini assitance', '3'),
(10, 'Maxi assitance', '3'),
(11, 'Extra assitance', '3'),
(12, 'Luxury', '4'),
(13, 'Standard', '4'),
(14, 'Basic', '4'),
(15, 'House', '5'),
(16, 'Aparment', '5'),
(17, 'HouseHoldItems', '5'),
(18, 'Fire', '6'),
(19, 'Earthquake', '6'),
(20, 'Robbery', '6'),
(21, 'Inventory Damage', '6'),
(22, 'General', '7'),
(23, 'Professional', '7'),
(24, 'House', '8'),
(25, 'Appartment', '8'),
(26, 'HouseholdItems', '8');

insert into customertype
values(1, 'Individual'),
(2, 'Company');

insert into paymenttype
values(1, 'Upfront'),
(2, 'In installments');

insert into settlement
values (1, 'Novo Lisice'),
(2, 'Trizla'),
(3, 'Drisla'),
(4, 'Zelenikovo'),
(5, 'Zlokukjani'),
(6, 'Zajas'),
(7, 'Zrnovce'),
(8, 'Ilinden'),
(9, 'Jegunovce'),
(10, 'Karbinci'),
(11, 'Karposh'),
(12, 'Kavadarci'),
(13, 'Kicevo'),
(14, 'Kocani'),
(15, 'Konce'),
(16, 'Kratovo'),
(17, 'Kriva Palanka'),
(18, 'Krusevo'),
(19, 'Kumanovo'),
(20, 'Lipkovo'),
(21, 'Lozovo'),
(22, 'Makedonska Kamenica'),
(23, 'Makedonski Brod'),
(24, 'Mavrovo and Rostusa'),
(25, 'Mogila'),
(26, 'Negotino'),
(27, 'Novaci'),
(28, 'Novo Selo'),
(29, 'Oslomej'),
(30, 'Ohrid'),
(31, 'Pehcevo'),
(32, 'Petrovec'),
(33, 'Plasnica'),
(34, 'Prilep'),
(35, 'Probistip'),
(36, 'Radovis'),
(37, 'Rankovce'),
(38, 'Resen'),
(39, 'Rosoman'),
(40, 'Sopiste'),
(41, 'Staro Nagoricane'),
(42, 'Stip'),
(43, 'Struga'),
(44, 'Strumica'),
(45, 'Studenicani'),
(46, 'Sveti Nikole'),
(47, 'Tearce'),
(48, 'Tetovo'),
(49, 'Valandovo'),
(50, 'Vasilevo'),
(51, 'Veles'),
(52, 'Vevcani'),
(53, 'Vinica'),
(54, 'Vranestica'),
(55, 'Vrapciste'),
(56, 'Zeleno sonce'),
(57, 'Zelino'),
(58, 'Zletovo'),
(59, 'Zrnovci'),
(60, 'Belovodica'),
(61, 'Berovci'),
(62, 'Varos'),
(63, 'Galichani'),
(64, 'Golem Radobil'),
(65, 'Mal Radobil'),
(66, 'Dabnica'),
(67, 'Dren'),
(68, 'Kadino Selo'),
(69, 'Krstec'),
(70, 'Lenishta'),
(71, 'Nikodin'),
(72, 'Novo Lagovo'),
(73, 'Staro Lagovo'),
(74, 'Oreovec'),
(75, 'Pletvar'),
(76, 'Prilepec'),
(77, 'Prisad'),
(78, 'Rakle'),
(79, 'Selce'),
(80, 'Slepche'),
(81, 'Smolani'),
(82, 'Toplica'),
(83, 'Trojaci'),
(84, 'Tsarevich'),
(85, 'Chumovo'),
(86, 'Shtavica'),
(87, 'Mazhuchishte'),
(88, 'Belitsa'),
(89, 'Benche'),
(90, 'Bitovo');

insert into state
values(1, 'Macedonia');